server:
  port: ${port:8089}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

######################################
#########  DB PROPERTIES #############
######################################
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PWD:test123}
    driver-class-name: ${DATASOURCE_DRIVERCLASS:org.postgresql.Driver}

routing:
  header: ${ROUTING_HEADER:testHeader}
  mappings:
    camt.059.001.06: ${ROUTING_CHANNEL2:camt59}




message:
  xpath:
    mappings:
#      pacs.008.001.09: ${MAPPING_PACS008://*[local-name()="CdtTrfTxInf"]}
      camt.059.001.04: ${MAPPING_CAMT59://*[local-name()="OrgnlNtfctnRef"]}

      # Add more message types and their XPaths as needed

errormessage:
  cam59: EPH

  bothSwitchMsg:
    - "f20"
    - "camt.059"

topic:
  fctopic: ${FCTOPIC:FCTOPIC}
  ephtopic: ${EPHTOPIC:EPHTOPIC}
  errortopic: ${EPH:EPH}
  dispatchertopic: ${DISPATCHERTOPIC:DISPATCHERTOPIC}
  sfmstopic: ${SFMSTOPIC:SFMSTOPIC}
  msgeventtrackertopic: ${MSGTOPIC:MSGEVENTTRACKERTOPIC}

cug_flag: ${CUG_FLAG:false}

mod_logic:
  mod_denominator: ${MOD_DENOMINATOR:100}
  eph_percentage: ${EPH_PERCENTAGE:30}